cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://matsutech.ti.com.br
spring:
  security:
    jwt:
      token:
        secret-key: 53cr37
        expire-length: 3600000
  datasource:
    url: jdbc:postgresql://localhost:49153/rest_with_spring_bootdb
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: none
  database:
    driverClassName: org.postgresql.Driver
  hibernate:
    show-sql: 'true'
